[[redirects]]
from = "/login"
to = "/index.html"
status = 200
query = { path = "login" }

[[redirects]]
from = "/register"
to = "/index.html"
status = 200
query = { path = "register" }

[[redirects]]
from = "/signup"
to = "/index.html"
status = 200
query = { path = "signup" }

[[redirects]]
from = "/info"
to = "/index.html"
status = 200
query = { path = "info" }

[[redirects]]
from = "/logout"
to = "/index.html"
status = 200
query = { path = "logout" }

[[redirects]]
from = "/signout"
to = "/index.html"
status = 200
query = { path = "signout" }

[[redirects]]
from = "/vote"
to = "/index.html"
status = 200
query = { path = "vote" }

[[redirects]]
from = "/dashboard"
to = "/index.html"
status = 200
query = { path = "dashboard" }

[[redirects]]
from = "/results"
to = "/index.html"
status = 200
query = { path = "results" }

[[redirects]]
from = "/comingsoon"
to = "/index.html"
status = 200
query = { path = "comingsoon" }

[[redirects]]
from = "/activation/:token"
to = "/index.html"
status = 200
query = { path = "activation", token = ":token" }

# Fallback redirect
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
